// <auto-generated />
using System;
using BriansLegacy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BriansLegacy.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260118223652_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BriansLegacy.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.ExtractedPageText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LibraryFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryFileId", "PageNumber");

                    b.ToTable("ExtractedPageTexts", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.FileDerivative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DerivativeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratorVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("LibraryFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryFileId", "DerivativeType", "GeneratorVersion", "InputHash")
                        .IsUnique();

                    b.ToTable("FileDerivatives", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.LibraryFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("LibraryItemId");

                    b.ToTable("LibraryFiles", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.LibraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletenessScore")
                        .HasColumnType("int");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("LibraryItems", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BriansLegacy.Models.LibraryItemCategory", b =>
                {
                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("LibraryItemId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("LibraryItemCategories", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.LibraryItemTag", b =>
                {
                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("LibraryItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("LibraryItemTags", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.ProcessingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CostEstimate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InputHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProcessorVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibraryItemId");

                    b.HasIndex("RunId");

                    b.HasIndex("StartedAt");

                    b.ToTable("ProcessingLogs", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.ProcessingState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("LastRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibraryItemId")
                        .IsUnique();

                    b.ToTable("ProcessingStates", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.ReviewQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AIExtractedData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldsNeedingReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LibraryItemId")
                        .IsUnique();

                    b.HasIndex("ReviewedAt");

                    b.ToTable("ReviewQueueItems", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("BriansLegacy.Models.BookDetails", b =>
                {
                    b.HasBaseType("BriansLegacy.Models.LibraryItem");

                    b.Property<string>("Author")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Edition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.ToTable("LibraryItems", t =>
                        {
                            t.Property("PageCount")
                                .HasColumnName("BookDetails_PageCount");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BriansLegacy.Models.DocumentDetails", b =>
                {
                    b.HasBaseType("BriansLegacy.Models.LibraryItem");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("BriansLegacy.Models.PlanDetails", b =>
                {
                    b.HasBaseType("BriansLegacy.Models.LibraryItem");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discipline")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DrawingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DrawingTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Revision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Scale")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SheetNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("BriansLegacy.Models.Category", b =>
                {
                    b.HasOne("BriansLegacy.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BriansLegacy.Models.ExtractedPageText", b =>
                {
                    b.HasOne("BriansLegacy.Models.LibraryFile", "LibraryFile")
                        .WithMany("ExtractedPages")
                        .HasForeignKey("LibraryFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryFile");
                });

            modelBuilder.Entity("BriansLegacy.Models.FileDerivative", b =>
                {
                    b.HasOne("BriansLegacy.Models.LibraryFile", "LibraryFile")
                        .WithMany("Derivatives")
                        .HasForeignKey("LibraryFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryFile");
                });

            modelBuilder.Entity("BriansLegacy.Models.LibraryFile", b =>
                {
                    b.HasOne("BriansLegacy.Models.LibraryItem", "LibraryItem")
                        .WithMany("Files")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("BriansLegacy.Models.LibraryItemCategory", b =>
                {
                    b.HasOne("BriansLegacy.Models.Category", "Category")
                        .WithMany("LibraryItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BriansLegacy.Models.LibraryItem", "LibraryItem")
                        .WithMany("Categories")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("BriansLegacy.Models.LibraryItemTag", b =>
                {
                    b.HasOne("BriansLegacy.Models.LibraryItem", "LibraryItem")
                        .WithMany("Tags")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BriansLegacy.Models.Tag", "Tag")
                        .WithMany("LibraryItems")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BriansLegacy.Models.ProcessingLog", b =>
                {
                    b.HasOne("BriansLegacy.Models.LibraryItem", "LibraryItem")
                        .WithMany("ProcessingLogs")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("BriansLegacy.Models.ProcessingState", b =>
                {
                    b.HasOne("BriansLegacy.Models.LibraryItem", "LibraryItem")
                        .WithOne("ProcessingState")
                        .HasForeignKey("BriansLegacy.Models.ProcessingState", "LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("BriansLegacy.Models.ReviewQueueItem", b =>
                {
                    b.HasOne("BriansLegacy.Models.LibraryItem", "LibraryItem")
                        .WithOne("ReviewQueueItem")
                        .HasForeignKey("BriansLegacy.Models.ReviewQueueItem", "LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("BriansLegacy.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("LibraryItems");
                });

            modelBuilder.Entity("BriansLegacy.Models.LibraryFile", b =>
                {
                    b.Navigation("Derivatives");

                    b.Navigation("ExtractedPages");
                });

            modelBuilder.Entity("BriansLegacy.Models.LibraryItem", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Files");

                    b.Navigation("ProcessingLogs");

                    b.Navigation("ProcessingState");

                    b.Navigation("ReviewQueueItem");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BriansLegacy.Models.Tag", b =>
                {
                    b.Navigation("LibraryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
